### ISSUE TITLE
Cannot use docker with Devstack

### ISSUE THREAD

**Issue by achanda** [docker-archive/openstack-docker#4]
I installed Devstack and Docker. Now when I tried to restart nova-compute, I got the following error:

2013-06-10 15:01:16.608 ERROR nova.openstack.common.threadgroup [-] Docker daemon is not running
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup Traceback (most recent call last):
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/openstack/common/threadgroup.py", line 117, in wait
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     x.wait()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/openstack/common/threadgroup.py", line 49, in wait
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     return self.thread.wait()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 168, in wait
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     return self._exit_event.wait()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 116, in wait
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     return hubs.get_hub().switch()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 187, in switch
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     return self.greenlet.switch()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 194, in main
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     result = function(_args, *_kwargs)
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/openstack/common/service.py", line 65, in run_service
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     service.start()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/service.py", line 155, in start
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     self.manager.init_host()
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/compute/manager.py", line 627, in init_host
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     self.driver.init_host(host=self.host)
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup   File "/opt/stack/nova/nova/virt/docker/driver.py", line 44, in init_host
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup     raise exception.NovaException("Docker daemon is not running")
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup NovaException: Docker daemon is not running
2013-06-10 15:01:16.608 TRACE nova.openstack.common.threadgroup

**Comment by jpetazzo** [comment]
Allow me to apologize for the dumb question, but: is docker running?

If it is—which version are you using? (Maybe you're using an old version, which doesn't have support for the REST API used by the Nova driver?)

Thank you!

**Comment by achanda** [comment]
Docker is actually not running, does not show up in `ps aux | grep docker`. I pulled the latest Devstack and Docker from git around an hour back. Do I need to install Docker separately? The installation doc does not say so!

**Comment by jpetazzo** [comment]
That's a very good point, we'll have to review those docs. Very sorry about that.

Meanwhile, all you have to do should be:

```
curl get.docker.io | sh
```

(Assuming that you're running a Debian or Ubuntu system; if you are running another distro, chances are that you will be missing AUFS support!)

**Comment by achanda** [comment]
On a closer look I realized that I do need to install docker separately. Thanks for the pointer. I am closing this issue now.

**Comment by samalba** [comment]
Yes, the driver needs Docker daemon to run on the side to function properly. That's the wanted behavior, but it's true that we should specify in the doc, I'll fix that. Thanks for testing!

**Comment by achanda** [comment]
I thought it might be useful to add a check in the installation script. I sent a pull request, feel free to merge or reject.
